Repository KiwiTalk/loco.rs, pull requests merged in 2020-05, with the labels that each got.

#4 agent를 선택할 수 있도록 변경
  src/internal/account.rs
  src/internal/agent.rs
  src/internal/client.rs
  src/internal/mod.rs
  src/tests/login.rs
Labels: enhancement

#6 Fix build error
  src/internal/account.rs
Labels: bug

#7 기기 등록 추가, test 폴더 이동
  src/internal/account.rs
  src/internal/client.rs
  src/internal/device_register_data.rs
  src/internal/mod.rs
  src/lib.rs
  src/tests/mod.rs
  tests/login.rs
  tests/mod.rs
  tests/register_device.rs
  tests/request_passcode.rs
Labels: enhancement

#9 Change: DeviceRegisterData wraps LoginData
  src/internal/account.rs
  src/internal/client.rs
  src/internal/device_register_data.rs
  tests/register_device.rs
Labels: enhancement

#15 Implement Chat Struct
  src/types/channel.rs
  src/types/chat/attachment.rs
  src/types/chat/attachment/file.rs
  src/types/chat/attachment/mod.rs
  src/types/chat/attachment/sharp.rs
  src/types/chat/attachment/sticker.rs
  src/types/chat/attachment/text.rs
  src/types/chat/feed.rs
  src/types/chat/mod.rs
  src/types/mod.rs
  src/types/structs/channel.rs
  src/types/user.rs
Labels: enhancement, refactor

#10 protocol_info 추가
  src/packet/mod.rs
  src/packet/protocol_info.rs
Labels: enhancement

#17 Implement custom_attachment
  src/types/chat/attachment/custom.rs
  src/types/chat/attachment/mod.rs
Labels: enhancement

#29 Add code linter
  .github/workflows/rust.yml
  src/internal/account.rs
  src/internal/agent.rs
  src/internal/device_register_data.rs
  src/internal/emoticon.rs
  src/internal/key.rs
  src/internal/language.rs
  src/internal/login_data.rs
  src/internal/mod.rs
  src/internal/token_client.rs
  src/internal/xvc_key.rs
  src/net/mod.rs
  src/packet/get_conf.rs
  src/packet/mod.rs
  src/packet/protocol_info.rs
  src/types/chat_room/attachment/custom.rs
  src/types/chat_room/attachment/sharp.rs
  src/types/chat_room/chat.rs
  src/types/chat_room/feed.rs
  src/types/chat_room/mod.rs
  src/types/mod.rs
  src/types/structs/mod.rs
  src/types/structs/open_link.rs
  src/types/user.rs
  tests/token_client.rs
Labels: enhancement
